# Version of Docker-compose
version: '3.8'
services:
  # Service name
  node:
    # Creating a custom image
    build:
      # Location to the Dockerfile
      context: ./server
      # Name of the Dockerfile
      dockerfile: Dockerfile
    ports:
        # External port:Internal port
      - 5000:8000
    volumes:
      # Syntax <nameOfVolume>:<directorInDocker>
      # ADD THE CONFIGURATION FROM THIS POINT to sync the working directory
      # for the application to the /app directory in the container
      - /server
      - /server/node_modules
    env_file:
      - ./server/.env
    depends_on:
      - mongo
  # Add the react service
  react:
    build:
      # Location to the dockerfile
      context: ./client
      # Name of the dockerfile
      dockerfile: Dockerfile
    volumes:
        # Bind-mounts configuration
      - /client/public
        # Ignoring any changes made in "node_modules" folder
      - /client/node_modules
    ports:
        # External port:Internal port
      - 3000:3000
    depends_on:
        # Starts up the node service before starting up the react service
      - node
    environment:
      # Enabling hot reload
      - CHOKIDAR_USEPOLLING=true
  mongo:
    image: mongo
    environment:
      MONGODB_USER: "$$DB_USER"
      MONGODB_PASS: "$$DB_PASSWORD"
      MONGODB_DATABASE: "$$DB_DATABASE"
      MONGO_INITDB_ROOT_USERNAME: "$$MONGO_INITDB_ROOT_USERNAME"
      MONGO_INITDB_ROOT_PASSWORD: "$$MONGO_INITDB_ROOT_PASSWORD"
      MONGO_INITDB_DATABASE: "$$MONGO_INITDB_DATABASE"
    env_file:
      - ./server/.env
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
      - ./server/config/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
# Making the node service volume accessible to other services.
volumes:
  # Declaring the node service volume.
  nodeVolume:
  mongo:
