#!/usr/bin/env bash

# Exit immediately if any subcommand fails
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

docker -v

command -v "docker" > /dev/null 2>&1 || {
  if [$(uname -s) = 'Darwin']; then
    # Install Homebrew
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    brew update

    # Install dependencies from Brewfile
    cd "$DIR/.."
    pwd

    brew bundle check >/dev/null 2>&1  || {
        echo "==> Installing Homebrew dependencies…"
        brew bundle
    }
  else
    sh "$DIR/install-docker.sh"
  fi
}

# React js dependencies
cd "$DIR/../client"
echo "==> Installing client dependencies"
npm install

# Copy env variables if env file does not exist
echo "==> Updating .env variables"
cp -r -n .env.example .env

# Node js dependencies
cd "$DIR/../server"
echo "==> Installing server dependencies"
npm install

# Copy env variables if env file does not exist
echo "==> Updating .env variables"
cp -r -n .env.example .env

cd "$DIR/.."
pwd 
echo "==> Docker Compose"
docker-compose up -d --build