name: heroku_deploy_prod

on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main, '*' ]
  pull_request: 
    branches: [ main, '*' ]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_PROD}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
    env:
      NODE_ENV: production